baseURL: https://vermillion-eclair-39abdc.netlify.app/
languageCode: en-us
title: Everything Everywhere all in R
theme: personal-web
googleAnalytics: ''
enableEmoji: yes
enableRobotsTXT: yes
pygmentsUseClasses: yes
pygmentsCodeFences: yes
params:
  accentColor: '#4B0082'
  assets:
    customCSS: ''
    favicon: ''
  breadcrumb: yes
  contact:
    email: ''
    text: ''
  intro:
    main: 'Everything Everywhere All in R'
    sub: A personal outlet for data exploration of movies, and hopefully other stuff.
  main:
    latestPublishHeader: Most recent post
  mainSections: post
  notFound:
    gopher: /images/groundug.png
    h1: Sorry, 
    p: this page does not exist.
  sections:
    portfolio: project
    post: article
  sidebar:
    backgroundImage: manchester.jpg
    gradientOverlay: ''
    logo: everything-R.png
  social:
    linkedin: https://www.linkedin.com/in/ismail-benchekroun1311/
taxonomies:
  design: designs
  tech: techs
blackfriday:
  hrefTargetBlank: yes
menu:
  main:
    - identifier: about
      name: About
      title: About section
      url: /about/
      weight: -120
    - identifier: portfolio
      name: Portfolio
      title: Portfolio
      url: /portfolio/
      weight: -110
    - identifier: blog
      name: Blog
      title: Blog section
      url: /post/
      weight: -100
    - identifier: contact
      name: Contact
      title: Contact
      url: /contact/
      weight: -90
sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5
privacy:
  googleAnalytics:
    anonymizeIP: yes
    disable: yes
    respectDoNotTrack: yes
    useSessionStorage: no
  twitter:
    disable: no
    enableDNT: yes
    simple: no
markup:
  goldmark:
    renderer:
      unsafe: yes
